# Generated by Django 5.1.6 on 2025-02-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Produtos',
        ),
    ]
